### ISSUE TITLE
Problem with  Gram matrix style loss in function get_style_cost_gram()

### ISSUE THREAD

**Issue by zerolocker** [machrisaa/stylenet#3]
In the function  stylenet_core.py : get_style_cost_gram, 

`layer_gram_lost = l2_norm_cost(G1 - G2) / (size ** 2)`

the code in function l2_norm_cost() already divides the result by (size ** 2), and in this line, the result is divided by (size ** 2) again. Is there a problem?

**Comment by machrisaa** [comment]
Nope, it is not a typo. The reason is that the calculation of the gram matrix will multiply the input by 2 times. So the one in the cost function is to calculate the mean from the sum, and the one you mentioned is to reduce the scale because of the product in the gram matrix calculation.

I add this in order to control the magnitude of the result. Otherwise, it will be affected by the input size and the hyperparameters need to be readjusted based on the size.
